@startmindmap
!include style.plantuml

+ Organisation
++ IndustryConsortium
++ InternationalOrganisation
++ NonProfitOrganisation
++ ForProfitOrganisation
-- GovernmentalOrganisation
-- NonGovernmentalOrganisation
-- ParentLegalEntity
-- SubsidiaryLegalEntity
-- AcademicScientificOrganisation

@endmindmap
