@startmindmap
!include style.plantuml

+ EntityInvolvement 
++ EntityActiveInvolvement
++ EntityPermissiveInvolvement
+++ OptingInToProcess
+++ OptingOutFromProcess
+++ ObjectingToProcess
+++ WithdrawingFromProcess
+++ ChallengingProcess
+++ ChallengingProcessOutput
+++ CorrectingProcess
+++ CorrectingProcessOutput
+++ ReversingProcessEffects
+++ ReversingProcessOutput
+++ ChallengingProcessInput
+++ CorrectingProcessInput
+++ ReversingProcessInput
-- EntityPassiveInvolvement
-- EntityNonInvolvement
-- EntityNonPermissiveInvolvement
--- CannotOptInToProcess
--- CannotOptOutFromProcess
--- CannotObjectToProcess
--- CannotWithdrawFromProcess
--- CannotChallengeProcess
--- CannotChallengeProcessOutput
--- CannotCorrectProcess
--- CannotCorrectProcessOutput
--- CannotReverseProcessEffects
--- CannotReverseProcessOutput
--- CannotChallengeProcessInput
--- CannotCorrectProcessInput
--- CannotReverseProcessInput

@endmindmap