@startuml
actor Person as P
entity Person_Agent as PA
database Agreement_Registry as R
entity Entity_Agent as PRA
actor Entity as SP

P --> R: choose agreement
note over P, PA: chooses SD-BASE, SD BASE-AT
P --> PA : Sets preference
note over P, SP: person visits website
PA --> PRA : do you support P7012 protocol?
PRA --> PA : P7012 supported, what are your preferred terms?

alt P7012 Supported
    PA --> PRA : SD-BASE as defined in Agreement_Registry
    
    alt SD-BASE is Acceptable
        PRA --> PA : SD-BASE accepted, let's execute a contract
        PA --> PRA : agreed (here is the signed contract)
        PRA --> PA : agreed (here is fully signed contract)
        note over PRA, PA : Contract is fully executed and is now in effect, both parties save a copy
    else SD-BASE is Unacceptable, but SD BASE-AT is Acceptable
        PRA --> PA : SD-BASE not accepted, is SD BASE-A negotiable?

        alt SD BASE-A is Acceptable
            PA --> PRA : SD BASE-A agreed (here is the signed contract)
            PRA --> PA : agreed (here is fully signed contract)
            note over PRA, PA : Negotiated Contract is fully executed and is now in effect, both parties save a copy
        else Term SD BASE-A is Not Acceptable
            PA --> PRA: SD BASE-A is not acceptable, negotiation is over
            note over PRA, PA : Contract process terminates
        else SD BASE-A is Unknown and not in Agreement_Registry
            PA --> PRA: SD BASE-A is not a recognised agreement, negotiation is over
        end
        PA --> PA : create a record of this interaction
    end
else P7012 Not Supported
    note over PRA, PA : No interaction takes place as person cannot assert their preferred agreement
end
@enduml