@startmindmap
!include style.plantuml

+ Purpose
++ AccountManagement
++ CommercialPurpose
++ CommunicationManagement
++ CommunicationForCustomerCare
++ CustomerManagement
++ EnforceSecurity
++ EstablishContractualAgreement
++ FulfilmentOfObligation
++ HumanResourceManagement
-- Marketing
-- NonCommercialPurpose
-- OrganisationGovernance
-- Personalisation
-- PublicBenefit
-- RecordManagement
-- ResearchAndDevelopment
-- ServiceProvision
-- VendorManagement

@endmindmap
