@startuml
!include style.plantuml
'left to right direction

package dpv {
    class Rule
    class Permission
    class Prohibition
    class Obligation
}
class Thing #silver

Thing -- Rule : hasRule >
Thing -- Permission : hasPermission >
Thing -- Prohibition : hasProhibition >
Thing -- Obligation : hasObligation >

Rule <|-u- Permission
Rule <|-u- Prohibition
Rule <|-u- Obligation

@enduml