@startuml
!include style.plantuml
'left to right direction

class Thing #silver
() Resource
package dpv {
	class Entity
	class LegalEntity
	class NaturalPerson
	class DataSubject
	class Representative
}

Thing -- Entity: hasEntity >
Entity <|-- LegalEntity

LegalEntity -- Resource: hasName >
LegalEntity -- Resource: hasContact >
LegalEntity -- Resource: hasIdentifier >
LegalEntity -- Resource: hasAddress >
LegalEntity -- Representative: hasRepresentataive >

Entity <|-- NaturalPerson
NaturalPerson <|-- DataSubject

@enduml
