@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
  	class Data
	class PersonalData
	class SpecialCategoryPersonalData
	class SensitivePersonalData
}

Thing -- PersonalData : hasPersonalData >
Thing -- Data : hasData >
Data <|-- PersonalData
PersonalData <|-- SensitivePersonalData
SensitivePersonalData <|-- SpecialCategoryPersonalData

@enduml
