@startuml
!include style.plantuml

class Thing #silver
package dpv {
    class Data
    class CollectedData
    class ObservedData
    class ProvidedData
    class CommerciallyConfidentialData
    class ConfidentialData
    class IntellectualPropertyData
    class StatisticallyConfidentialData
    class DerivedData
    class InferredData
    class GeneratedData
    class SyntheticData
    class IncorrectData
    class NonPersonalData
    class AnonymisedData
    class SensitiveData
    class SensitiveNonPersonalData
    class UnverifiedData
    class VerifiedData
    class PersonalData
    class CollectedPersonalData
    class DerivedPersonalData
    class GeneratedPersonalData
    class IdentifyingPersonalData
    class PseudonymisedData
    class SensitivePersonalData
    class SpecialCategoryPersonalData
    class InferredPersonalData
    class ObservedPersonalData
    class ProvidedPersonalData
    class ContextuallyAnonymisedData
}

Thing -- PersonalData : hasPersonalData >
Thing -- Data : hasData >

Data <|-- CollectedData
CollectedData <|-- CollectedPersonalData
CollectedPersonalData <|-- ObservedPersonalData
CollectedPersonalData <|-- ProvidedPersonalData
CollectedData <|-- ObservedData
CollectedData <|-- ProvidedData
ObservedData <|-- ObservedPersonalData
ProvidedData <|-- ProvidedPersonalData
Data <|-- CommerciallyConfidentialData
Data <|-- ConfidentialData
ConfidentialData <|-- IntellectualPropertyData
ConfidentialData <|-- StatisticallyConfidentialData
Data <|-- DerivedData
DerivedData <|-- DerivedPersonalData
DerivedPersonalData <|-- InferredPersonalData
DerivedData <|-- InferredData
InferredData  <|-- InferredPersonalData
Data <|-- GeneratedData
GeneratedData <|-- SyntheticData
StatisticallyConfidentialData -[hidden]- NonPersonalData
StatisticallyConfidentialData -[hidden]- GeneratedData
VerifiedData -[hidden]- SensitiveNonPersonalData
CollectedData -[hidden]- GeneratedPersonalData
Data <|-- IncorrectData
Data <|-- NonPersonalData
NonPersonalData <|-- AnonymisedData
Data <|-- PersonalData
PersonalData <|-- CollectedPersonalData
PersonalData <|-- DerivedPersonalData
PersonalData <|-- GeneratedPersonalData
PersonalData <|-- IdentifyingPersonalData
PersonalData <|-- PseudonymisedData
PseudonymisedData <|-- ContextuallyAnonymisedData
PersonalData <|-- SensitivePersonalData
SensitivePersonalData <|-- SpecialCategoryPersonalData
Data <|-- SensitiveData
SensitiveData <|-- SensitiveNonPersonalData
Data <|-- UnverifiedData
Data <|-- VerifiedData

@enduml