#!/usr/bin/env bash
#
# Author: Harshvardhan J. Pandit
# Generated by: ChatGPT (gpt-4, 2025-08-03)
#
# Usage: ./spellcheck.sh filename

FILE="$1"
PWS_PATH="aspell/en_GB.pws"

# Determine aspell mode based on file extension
case "${FILE##*.}" in
  html|htm|j2|jinja2)
    MODE="html"
    ;;
  ttl|rdf|csv)
    MODE="none"
    ;;
  *)
    MODE="none"
    ;;
esac

# Ensure aspell directory and personal dictionary file exist
mkdir -p "$(dirname "$PWS_PATH")"
if [ ! -f "$PWS_PATH" ]; then
    echo $'personal_ws-1.1 en 0' > "$PWS_PATH"
fi

# Run aspell with explicit personal dictionary file
aspell --lang=en_GB --mode="$MODE" --personal="$PWD/$PWS_PATH" check "$FILE"
