
DPV_VERSION = "2.2-dev"
DPV_PREVIOUS_VERSION = "2.1"
DPV_STABLE_VERSION = "2.1"
DPV_STABLE_PREVIOUS_VERSION = "2.0"

DPV_PUBLISH_DATE = "2025-02-01"

# Document status: should be one of CG-DRAFT or CG-FINAL
DOCUMENT_STATUS = "CG-DRAFT"
assert(DOCUMENT_STATUS in ('CG-FINAL', 'CG-DRAFT'))