@startuml
!include style.plantuml
'left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class RiskAssessment
	class RightsImpactAssessment
	class DPIA
	class DataBreachImpactAssessment
	class Assessment
	class FRIA
	class ImpactAssessment
	class PIA
	class DataTransferImpactAssessment
	class ReviewImpactAssessment
}
Assessment <|-l- RiskAssessment
Thing -- Assessment : hasAssessment >
Thing -- RiskAssessment : hasRiskAssessment >
Assessment <|-- ImpactAssessment
Thing -- ImpactAssessment : hasImpactAssessment >
ImpactAssessment <|-- RightsImpactAssessment
ImpactAssessment <|-- PIA
ImpactAssessment <|-- DataTransferImpactAssessment
ImpactAssessment <|-- ReviewImpactAssessment
RightsImpactAssessment <|-- DPIA
RightsImpactAssessment <|-- DataBreachImpactAssessment
RightsImpactAssessment <|-- FRIA


@enduml
