@startmindmap
!include style.plantuml

+ LegalBasis
++ Consent
+++ InformedConsent
++++ ExpressedConsent
+++++ ExplicitlyExpressedConsent
++++ ImpliedConsent
+++ UninformedConsent
++ Contract
+++ EnterIntoContract
+++ ContractPerformance
++ PublicInterest
++ LegalObligation
-- DataTransferLegalBasis
-- LegitimateInterest
--- LegitimateInterestOfController
--- LegitimateInterestOfDataSubject
--- LegitimateInterestOfThirdParty
-- OfficialAuthorityOfController
-- VitalInterest
--- VitalInterestOfNaturalPerson
---- VitalInterestOfDataSubject

@endmindmap
