@startuml
!include style.plantuml
left to right direction
skinparam groupInheritance 2

class Thing #silver
package dpv {
    class Entity
    package Automation <<Rectangle>> #line.dashed {
        class AutomationLevel
        class AssistiveAutomation
        class Autonomous
        class ConditionalAutomation
        class FullAutomation
        class HighAutomation
        class NotAutomated
        class PartialAutomation
    }
    package Involvement <<Rectangle>> #line.dashed {
        class EntityInvolvement
        package Permissive <<Rectangle>> {
            class EntityPermissiveInvolvement
            class OptingInToProcess
            class OptingOutFromProcess
            class ObjectingToProcess
            class WithdrawingFromProcess
            class ChallengingProcess
            class ChallengingProcessOutput
            class CorrectingProcess
            class CorrectingProcessOutput
            class ReversingProcessEffects
            class ReversingProcessOutput
            class ChallengingProcessInput
            class CorrectingProcessInput
            class ReversingProcessInput
        }
        package NonPermissive <<Rectangle>> #line.dashed {
            class EntityNonPermissiveInvolvement
            class CannotOptInToProcess
            class CannotOptOutFromProcess
            class CannotObjectToProcess
            class CannotWithdrawFromProcess
            class CannotChallengeProcess
            class CannotChallengeProcessOutput
            class CannotCorrectProcess
            class CannotCorrectProcessOutput
            class CannotReverseProcessEffects
            class CannotReverseProcessOutput
            class CannotChallengeProcessInput
            class CannotCorrectProcessInput
            class CannotReverseProcessInput
        }
        class EntityActiveInvolvement
        class EntityPassiveInvolvement
        class EntityNonInvolvement
        package Human <<Rectangle>> #line.dashed { 
            class HumanInvolvement
            class HumanInvolved
            class HumanInvolvementForControl
            class HumanInvolvementForIntervention
            class HumanInvolvementForDecision
            class HumanInvolvementForInput
            class HumanInvolvementForOversight
            class HumanInvolvementForVerification
            class HumanNotInvolved
        }
    }
}

Thing -- AutomationLevel : hasAutomationLevel
AutomationLevel <|-- AssistiveAutomation
AutomationLevel <|-- Autonomous
AutomationLevel <|-- ConditionalAutomation
AutomationLevel <|-- FullAutomation
AutomationLevel <|-- HighAutomation
AutomationLevel <|-- NotAutomated
AutomationLevel <|-- PartialAutomation

Thing -- EntityInvolvement : hasEntityInvolvement
EntityInvolvement <|-- EntityPermissiveInvolvement
EntityInvolvement <|-- EntityNonPermissiveInvolvement
EntityInvolvement <|-- EntityActiveInvolvement
EntityInvolvement <|-- EntityPassiveInvolvement
EntityInvolvement <|-- EntityNonInvolvement

Thing -- Entity : hasActiveEntity
Thing -- Entity : hasPassiveEntity
Thing -- Entity : hasNonInvolvementEntity
Thing -- Entity : isDeterminedByEntity

Entity -[hidden]- EntityInvolvement

EntityPermissiveInvolvement <|-- OptingInToProcess
EntityPermissiveInvolvement <|-- OptingOutFromProcess
EntityPermissiveInvolvement <|-- ObjectingToProcess
EntityPermissiveInvolvement <|-- WithdrawingFromProcess
EntityPermissiveInvolvement <|-- ChallengingProcess
EntityPermissiveInvolvement <|-- ChallengingProcessOutput
EntityPermissiveInvolvement <|-- CorrectingProcess
EntityPermissiveInvolvement <|-- CorrectingProcessOutput
EntityPermissiveInvolvement <|-- ReversingProcessEffects
EntityPermissiveInvolvement <|-- ReversingProcessOutput
EntityPermissiveInvolvement <|-- ChallengingProcessInput
EntityPermissiveInvolvement <|-- CorrectingProcessInput
EntityPermissiveInvolvement <|-- ReversingProcessInput

OptingInToProcess -[hidden]- EntityNonPermissiveInvolvement
EntityActiveInvolvement -[hidden]- HumanInvolvement

EntityNonPermissiveInvolvement <|-- CannotOptInToProcess
EntityNonPermissiveInvolvement <|-- CannotOptOutFromProcess
EntityNonPermissiveInvolvement <|-- CannotObjectToProcess
EntityNonPermissiveInvolvement <|-- CannotWithdrawFromProcess
EntityNonPermissiveInvolvement <|-- CannotChallengeProcess
EntityNonPermissiveInvolvement <|-- CannotChallengeProcessOutput
EntityNonPermissiveInvolvement <|-- CannotCorrectProcess
EntityNonPermissiveInvolvement <|-- CannotCorrectProcessOutput
EntityNonPermissiveInvolvement <|-- CannotReverseProcessEffects
EntityNonPermissiveInvolvement <|-- CannotReverseProcessOutput
EntityNonPermissiveInvolvement <|-- CannotChallengeProcessInput
EntityNonPermissiveInvolvement <|-- CannotCorrectProcessInput
EntityNonPermissiveInvolvement <|-- CannotReverseProcessInput

Thing -- HumanInvolvement : hasHumanInvolvement
HumanInvolvement <|-- HumanInvolved
HumanInvolvement <|-- HumanInvolvementForControl
HumanInvolvement <|-- HumanInvolvementForIntervention
HumanInvolvement <|-- HumanInvolvementForDecision
HumanInvolvement <|-- HumanInvolvementForInput
HumanInvolvement <|-- HumanInvolvementForOversight
HumanInvolvement <|-- HumanInvolvementForVerification
HumanInvolvement <|-- HumanNotInvolved

@enduml