@startuml
!include style.plantuml
'left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Assessment
	class RiskAssessment
	class ImpactAssessment
	class RightsImpactAssessment
	class DPIA
	class DataBreachImpactAssessment
	class FRIA
	class PIA
	class DataTransferImpactAssessment
	class ReviewImpactAssessment
}
Thing -- Assessment : hasAssessment >
Assessment <|-- RiskAssessment
Assessment <|-- ImpactAssessment
ImpactAssessment <|-- RightsImpactAssessment
ImpactAssessment <|-- PIA
ImpactAssessment <|-- DataTransferImpactAssessment
ImpactAssessment <|-- ReviewImpactAssessment
RightsImpactAssessment <|-- DPIA
RightsImpactAssessment <|-- DataBreachImpactAssessment
RightsImpactAssessment <|-- FRIA


@enduml
