@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class DataProcessor
	class DataController
	class ThirdParty
	class Recipient
}
Recipient <|-- ThirdParty
Recipient <|-- DataController
Recipient <|-- DataProcessor

Thing -- Recipient : hasRecipient >
Thing -- DataController: hasRecipientDataController >
Thing -- DataProcessor: hasRecipientDataProcessor >
Thing -- ThirdParty : hasRecipientThirdParty >


@enduml
