name: Fix Typo or Error
description: Fix typo(s) or error(s) in RDF and HTML documents
title: "[FIX]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: dropdown
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification(s) are affected by this
      multiple: true
      options:
        - DPV
        - Personal Data (PD)
        - Technical (TECH)
        - Locations (LOC)
        - RISK
        - AI
        - Justifications
        - LEGAL (e.g. IE, US)
        - EU-GDPR
        - EU-DGA
        - EU-NIS2
        - EU-AIAct
        - EU-Rights
        - Other
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: Please list all typo(s), error(s), etc. here
      placeholder: Errors can be typo(s), missing or broken links, missing images, wrong references, incorrect attributions...
      value: Fix ...
    validations:
      required: true
