name: How to use DPV for...?
description: Ask question(s) for how to use DPV for a specific application
title: "[HOW]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to participate!
  - type: dropdown
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification the question is about
      multiple: true
      options:
        - DPV
        - Personal Data (PD)
        - Technical (TECH)
        - Locations (LOC)
        - RISK
        - AI
        - Justifications
        - LEGAL (e.g. IE, US)
        - EU-GDPR
        - EU-DGA
        - EU-NIS2
        - EU-AIAct
        - EU-Rights
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is the question or suggestion?
      value: ...
    validations:
      required: true
