name: Suggest New Concept(s)
description: Suggest new concept(s) existing concept(s)
title: "[NEW]: "
labels: ["todo", "proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out to participate!
  - type: dropdown
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification(s) are affected by this
      multiple: true
      options:
        - DPV
        - Personal Data (PD)
        - Technical (TECH)
        - Locations (LOC)
        - RISK
        - AI
        - Justifications
        - LEGAL (e.g., IE, US)
        - EU-GDPR
        - EU-DGA
        - EU-NIS2
        - EU-AIAct
        - EU-Rights
        - Other
    validations:
      required: true
  - type: textarea
    id: new
    attributes:
      label: New Concept(s)
      description: Please list all proposed new concept(s) here, using the following structure
      value: |
        Term: (used as unique ID)
        Label: (human label)
        Definition: (definition or description of term)
        Parent term: (existing term in DPV)
        Source: (url or reference)
        Usage note: (considerations when using the term e.g. scope, caution)
    validations:
      required: false