name: Suggest New or Change Existing Concept(s)
description: Suggest new concept(s) or change existing concept(s)
title: "[Concept]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out to participate!
  - type: dropdown
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification is affected by this
      multiple: true
      options:
        - DPV
        - Personal Data (PD)
        - Technical (TECH)
        - Locations (LOC)
        - RISK
        - AI
        - Justifications
        - LEGAL (e.g. IE, US)
        - EU-GDPR
        - EU-DGA
        - EU-NIS2
        - EU-AIAct
        - EU-Rights
    validations:
      required: true
  - type: textarea
    id: new
    attributes:
      label: New Concept(s)
      description: Please list all proposed new concept(s) here using the following structure
      value: |
        Term: e.g. NewConcept
        Label: e.g. New Concept
        Definition: e.g. this concept represents new concept
        Parent term: e.g. Parent Concept
        Source: e.g. https://example.com or ISO-XYZ
        Usage note: e.g. this concept should be used with specific consideration
    validations:
      required: false
  - type: textarea
    id: change
    attributes:
      label: Changed Concept(s)
      description: Please list all proposed changes to existing concept(s) here using the following structure
      value: |
        Existing Term: e.g. dpv:NewConcept or risk:NewConcept
        Change: e.g. change label from X to Y, or add usage note stating "xyz"
        Justification: optional comment for why the change should be made
    validations:
      required: false
