@startuml
!include style.plantuml
left to right direction

package dpv {
    class Technology
    class Process
    class "Data "
    class Purpose
}

package ai {
    class AI
    class Capability
    class Technique
    class Data
}

Process -- Technology : dpv:isImplementedUsingTechnology >
Process -- "Data " : dpv:hasData >
Process -- Purpose : dpv:hasPurpose >
Technology <|-- AI
AI -- Capability : ai:hasCapability >
Capability -- Technique : ai:hasTechnique >
Technique -- Data : ai:hasData >
"Data " <|-- Data

note top of Purpose : identity authentication
note top of Process : unlocking phone using face recognition
note right of "Data " : user profile
note bottom of Capability : facial recognition
note top of Technique : deep learning
note top of Data : user facial profile

@enduml