@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
    package Automation <<Rectangle>> #line.dashed {
        class AutomationLevel
        class AssistiveAutomation
        class Autonomous
        class ConditionalAutomation
        class FullAutomation
        class HighAutomation
        class NotAutomated
        class PartialAutomation
    }
    package Human <<Rectangle>> #line.dashed { 
        class EntityInvolvement
        class HumanInvolvement
        class HumanInvolved
        class HumanInvolvementForControl
        class HumanInvolvementForIntervention
        class HumanInvolvementForDecision
        class HumanInvolvementForInput
        class HumanInvolvementForOversight
        class HumanInvolvementForVerification
        class HumanNotInvolved
    }
}

Thing -- AutomationLevel : hasAutomationLevel >
AutomationLevel <|-- AssistiveAutomation
AutomationLevel <|-- Autonomous
AutomationLevel <|-- ConditionalAutomation
AutomationLevel <|-- FullAutomation
AutomationLevel <|-- HighAutomation
AutomationLevel <|-- NotAutomated
AutomationLevel <|-- PartialAutomation

Thing -- EntityInvolvement : hasEntityInvolvement >
Thing -- HumanInvolvement : hasHumanInvolvement >
EntityInvolvement <|--- HumanInvolvement
HumanInvolvement <|-- HumanInvolved
HumanInvolvement <|-- HumanInvolvementForControl
HumanInvolvement <|-- HumanInvolvementForIntervention
HumanInvolvement <|-- HumanInvolvementForDecision
HumanInvolvement <|-- HumanInvolvementForInput
HumanInvolvement <|-- HumanInvolvementForOversight
HumanInvolvement <|-- HumanInvolvementForVerification
HumanInvolvement <|-- HumanNotInvolved

@enduml