@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class c1 as "Concept"
class c2 as "Concept"
class c3 as "Concept"
class c4 as "Concept"
c1 <|- c3
c2 -- c3 : isInstanceOf >
c3 -- c4 : relation >

@enduml
