@startuml 
!include style.plantuml

class Thing #silver

package dpv {
    class DataSource
    class DataSubjectDataSource
    class DataPublishedByDataSubject
    class DataControllerDataSource
    class ThirdPartyDataSource
    class PublicDataSource
    class NonPublicDataSource
    class DataSubject
    class DataController
    class ThirdParty
}

Thing -- DataSource : hasDataSource >

DataSource <|-- DataSubjectDataSource
DataSubjectDataSource <|-- DataPublishedByDataSubject
DataSource <|-- DataControllerDataSource
DataSource <|-- ThirdPartyDataSource
DataSource <|-- PublicDataSource
DataSource <|-- NonPublicDataSource

DataSubjectDataSource .. DataSubject
DataPublishedByDataSubject .. DataSubject
DataControllerDataSource .. DataController
ThirdPartyDataSource .. ThirdParty
@enduml