@startuml
!include style.plantuml
'left to right direction

class Thing #silver
Thing -r- dpv.Process : hasProcess >
package dpv {
	
	' Core Concepts
	class Process #LightSalmon
	class Data #LightSalmon
	class PersonalData
	class Purpose #LightBlue
	class DataController
	class DataSubject
	class Recipient #LightBlue
	class Context #LightBlue
	class Risk #LightBlue
	class OrgnaizationalMeasure #LightBlue
	class TechnicalMeasure #LightBlue
	class Right #LightBlue
	class LegalBasis #LightBlue
	class Processing #LightBlue
	class Technology #LightBlue
	
	PersonalData -u-|>Data
	
	Process -u- Purpose: hasPurpose >
	Process -u- Processing: hasProcessing >
	Process -u- DataController: hasDataController >
	Process -u- DataSubject: hasDataSubject >
	Process -u- LegalBasis: hasLegalBasis >
	Process -u- Right: hasRight >
	Process -u- Risk: hasRisk >
	Process -- PersonalData : hasPersonalData >
	Process -- Data: hasData >
	Process -- Recipient: hasRecipient >
	Process -- TechnicalMeasure: hasTechnicalMeasure >
	Process -- OrgnaizationalMeasure: hasOrganizationalMeasure >
	Process -- Context: hasContext >
	Process -- Technology: isImplementedUsingTechnology >

	}
	

	
	@enduml
