@startwbs
!include style.plantuml

* Entity
** NaturalPerson
*** DataSubject
**** Adult
**** Child
**** ParentOfDataSubject
**** VulnerableDataSubject
*** Representative
** LegalEntity
*** DataController
*** JointDataControllers
*** DataExporter
*** Recipient
**** DataImporter
**** DataProcessor
**** ThirdParty
*** ServiceConsumer
*** ServiceProvider
** Organisation
*** GovernmentalOrganisation
**** Authority
***** DataProtectionAuthority
***** NationalAuthority
***** RegionalAuthority
***** SupraNationalAuthority
*** AcademicScientificOrganisation
*** ForProfitOrganisation
*** IndustryConsortium
*** InternationalOrganisation
*** NonGovernmentalOrganisation
*** NonProfitOrganisation

@endwbs