@startuml
!include style.plantuml
skinparam groupInheritance 2
left to right direction

package dpv {
	class Process
	class TechnicalOrganisationalMeasure
	class OrganisationalMeasure
}
package dpv.legal.eu.gdpr {
	class DataTransferTool
	class AdHocContractualClauses
	class BindingCorporateRules
	class CertificationMechanismsForDataTransfers
	class CodesOfConductForDataTransfers
	class SCCByCommission
	class SCCBySupervisoryAuthority
	class StandardContractualClauses
	class SupplementaryMeasure
}

Process -u TechnicalOrganisationalMeasure : hasTechnicalOrganisationalMeasure >
TechnicalOrganisationalMeasure <|-l- OrganisationalMeasure
OrganisationalMeasure <|-- DataTransferTool
OrganisationalMeasure <|-- AdHocContractualClauses
OrganisationalMeasure <|-- BindingCorporateRules
OrganisationalMeasure <|-- CertificationMechanismsForDataTransfers
OrganisationalMeasure <|-- CodesOfConductForDataTransfers
OrganisationalMeasure <|-- SCCByCommission
OrganisationalMeasure <|-- SCCBySupervisoryAuthority
OrganisationalMeasure <|-- StandardContractualClauses
OrganisationalMeasure <|-- SupplementaryMeasure

@enduml
