@startuml
!include style.plantuml
skinParam groupInheritance 2

package dpv {
	class Process
	class LegalBasis
}
package dpv.legal.eu.gdpr {
	class A45_3 as "A45-3"
	class A46_2_a as "A46-2-a"
	class A46_2_b as "A46-2-b"
	class A46_2_c as "A46-2-c"
	class A46_2_d as "A46-2-d"
	class A46_2_e as "A46-2-e"
	class A46_2_f as "A46-2-f"
	class A46_3_a as "A46-3-a"
	class A46_3_b as "A46-3-b"
	class A49_1_a as "A49-1-a"
	class A49_1_b as "A49-1-b"
	class A49_1_c as "A49-1-c"
	class A49_1_d as "A49-1-d"
	class A49_1_e as "A49-1-e"
	class A49_1_f as "A49-1-f"
	class A49_1_g as "A49-1-g"
	class A49_2 as "A49-2"
}

Process -- LegalBasis: hasLegalBasis >

LegalBasis <|-- A45_3
LegalBasis <|-- A46_2_a
LegalBasis <|-- A46_2_b
LegalBasis <|-- A46_2_c
LegalBasis <|-- A46_2_d
LegalBasis <|-- A46_2_e
LegalBasis <|-- A46_2_f
LegalBasis <|-- A46_3_a
LegalBasis <|-- A46_3_b
LegalBasis <|-- A49_1_a
LegalBasis <|-- A49_1_b
LegalBasis <|-- A49_1_c
LegalBasis <|-- A49_1_d
LegalBasis <|-- A49_1_e
LegalBasis <|-- A49_1_f
LegalBasis <|-- A49_1_g
LegalBasis <|-- A49_2

@enduml
