@startuml
!include style.plantuml
'skinparam groupInheritance 2

class Thing #silver
package dpv {
    class Entity
    class EntityInvolvement
    class EntityPermissiveInvolvement
    class EntityNonPermissiveInvolvement
    class EntityActiveInvolvement
    class EntityPassiveInvolvement
    class EntityNonInvolvement
}

Thing -- EntityInvolvement : hasEntityInvolvement >
EntityInvolvement <|-- EntityPermissiveInvolvement
EntityInvolvement <|-- EntityNonPermissiveInvolvement
EntityInvolvement <|-- EntityActiveInvolvement
EntityInvolvement <|-- EntityPassiveInvolvement
EntityInvolvement <|-- EntityNonInvolvement

Thing -- Entity : "hasActiveEntity\nhasPassiveEntity\nhasNonInvolvementEntity\nisDeterminedByEntity" >

@enduml