@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Technology
}
Thing -- Technology: isImplementedUsingTechnology >
Technology -- Thing: implements >


@enduml
