@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class PersonalData
	class SpecialCategoryPersonalData
	class SensitivePersonalData
}

Thing -- PersonalData : hasPersonalData >
PersonalData <|-- SensitivePersonalData
SensitivePersonalData <|-- SpecialCategoryPersonalData

@enduml
