@startuml
!include style.plantuml
left to right direction
''top to bottom direction

class Thing #silver
package dpv {
	class AnonymisedData
	class CollectedData
	class CollectedPersonalData
	class CommerciallyConfidentialData
	class ConfidentialData
	class ContextuallyAnonymisedData
	class Data
	class DerivedData
	class DerivedPersonalData
	class GeneratedData
	class GeneratedPersonalData
	class IdentifyingPersonalData
	class IncorrectData
	class InferredData
	class InferredPersonalData
	class IntellectualPropertyData
	class NonPersonalData
	class ObservedData
	class ObservedPersonalData
	class PersonalData
	class ProvidedData
	class ProvidedPersonalData
	class PseudonymisedData
	class SensitiveData
	class SensitiveNonPersonalData
	class SensitivePersonalData
	class SpecialCategoryPersonalData
	class StatisticallyConfidentialData
	class SyntheticData
	class UnverifiedData
	class VerifiedData
}

CollectedData <|-- CollectedPersonalData
CollectedData <|-- ObservedData
CollectedData <|-- ProvidedData
CollectedPersonalData <|-- ObservedPersonalData
CollectedPersonalData <|-- ProvidedPersonalData
ConfidentialData <|-- IntellectualPropertyData
ConfidentialData <|-- StatisticallyConfidentialData
Data <|-- CollectedData
Data <|-- CommerciallyConfidentialData
Data <|-- ConfidentialData
Data <|-- DerivedData
Data <|-- GeneratedData
Data <|-- IncorrectData
Data <|-- NonPersonalData
Data <|-- PersonalData
Data <|-- SensitiveData
Data <|-- UnverifiedData
Data <|-- VerifiedData
DerivedData <|–- DerivedPersonalData
DerivedData <|–- InferredData
DerivedPersonalData <|-- InferredPersonalData
GeneratedData <|-- SyntheticData
InferredData <|-- InferredPersonalData
NonPersonalData <|-- AnonymisedData
ObservedData <|-- ObservedPersonalData
PersonalData <|-- CollectedPersonalData
PersonalData <|-- SensitivePersonalData
PersonalData <|–- DerivedPersonalData
PersonalData <|–- GeneratedPersonalData
PersonalData <|–- IdentifyingPersonalData
PersonalData <|–- PseudonymisedData
ProvidedData <|-- ProvidedPersonalData
PseudonymisedData <|-- ContextuallyAnonymisedData
SensitiveData <|-- SensitiveNonPersonalData
SensitiveData <|-- SensitivePersonalData
SensitivePersonalData <|-- SpecialCategoryPersonalData
Thing -- Data : hasData >
Thing -- PersonalData : hasPersonalData >



@enduml
