@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Technology
	class Entity
	class Location
}
package dpv.tech {
	class Actor
	class Capability
	class ProvisionMethod
	class CommunicationMechanism
	class InputOutput
	class Documentation
	class DeploymentLocation
	class Function
	class IntendedUse
}
' Technology
Thing -- Technology: isImplementedUsingTechnology >
Technology -- Thing: implements >

' Actor
Entity <|-- Actor
Thing -- Actor: hasActor >
Thing -- Entity: hasEntity >

' Capability
Thing -- Capability: hasCapability >

' ProvisionMethod
Technology <|-- ProvisionMethod

' CommunicationMechanism
Technology <|-- CommunicationMechanism

' InputOutput

' Documentation
Thing -- Documentation: hasDocumentation >

' DeploymentLocation
Thing -- Location: hasLocation >
Location <|-- DeploymentLocation

' Function
Thing -- Function: hasFunction >

' IntendedUse
Thing -- IntendedUse: hasIntendedUse >

@enduml
