@startuml
actor Person as P
entity Person_Agent as PA
database Agreement_Registry as R
entity Entity_Agent as PRA
actor Entity as SP

P --> R: choose agreement
note over P, PA: chooses SD-BY, SD BY-AT
P --> PA : Sets preference
note over P, SP: person visits website
PA --> PRA : do you support P7012 protocol?
PRA --> PA : P7012 supported, what are your preferred terms?

alt P7012 Supported
    PA --> PRA : SD-BY as defined in Agreement_Registry
    PRA --> PRA : do I know what is SD-BY?
    alt Entity_Agent knows SD-BY
      PRA --> PRA: assess SD-BY
    
    else Entity_Agent does not know SD-BY
      PRA --> R: retrieve terms in format X
      R --> PRA: here are terms in format X
      SP --> PRA : assess terms, set preferences for future
    end
    
    alt SD-BY is Acceptable
        PRA --> PA : SD-BY accepted, let's execute a contract
        PA --> PRA : agreed (here is the signed contract)
        PRA --> PA : agreed (here is fully signed contract)
        note over PRA, PA : Contract is fully executed and is now in effect, both parties save a copy
    else SD-BY is Unacceptable, but SD BY-AT is Acceptable
        PRA --> PA : SD-BY not accepted, is SD BY-A negotiable?
        alt PA knows SD BY-A
          PA --> PA : assess SD BY-A
        else PA does not know SD BY-A
          PA --> R: retrieve SD BY-A in format X
          R --> PA: SD BY-A in format X
          PA --> PA: is it compatible with preferences?
        end
        alt SD BY-A is Acceptable
            PA --> PRA : SD BY-A agreed (here is the signed contract)
            PRA --> PA : agreed (here is fully signed contract)
            note over PRA, PA : Negotiated Contract is fully executed and is now in effect, both parties save a copy
        else Term SD BY-A is Not Acceptable
            PA --> PRA: SD BY-A is not acceptable, negotiation is over
            note over PRA, PA : Contract process terminates
        else SD BY-A is Unknown and not in Agreement_Registry
            PA --> PRA: SD BY-A is not a recognised agreement, negotiation is over
        end
        PA --> PA : create a record of this interaction
    end
else P7012 Not Supported
    note over PRA, PA : No interaction takes place as person cannot assert their preferred agreement
end
@enduml