@startwbs

* TechnicalMeasure
** AccessControlMethod
*** UsageControl
** ActivityMonitoring
** AuthenticationProtocols
*** BiometricAuthentication
*** CryptographicAuthentication
*** MultiFactorAuthentication
*** PasswordAuthentication
*** SingleSignOn
*** ZeroKnowledgeAuthentication
** AuthorisationProtocols
** CryptographicMethods
*** AsymmetricCryptography
*** CryptographicAuthentication
*** CryptographicKeyManagement
*** DifferentialPrivacy
*** DigitalSignatures
*** HashFunctions
*** HomomorphicEncryption
*** PostQuantumCryptography
*** PrivacyPreservingProtocol
*** PrivateInformationRetrieval
*** QuantumCryptography
*** SecretSharingSchemes
*** SecureMultiPartyComputation
*** SymmetricCryptography
*** TrustedComputing
*** TrustedExecutionEnvironment
*** ZeroKnowledgeAuthentication
** DataBackupProtocols
** DataSanitisationTechnique
*** DataRedaction
*** Deidentification
** DigitalRightsManagement
** Encryption
*** AsymmetricEncryption
*** EncryptionAtRest
*** EncryptionInTransfer
*** EncryptionInUse
*** EndToEndEncryption
*** SymmetricEncryption
** InformationFlowControl
** SecurityMethod
*** DistributedSystemSecurity
*** DocumentSecurity
*** FileSystemSecurity
*** HardwareSecurityProtocols
*** IntrusionDetectionSystem
*** MobilePlatformSecurity
*** NetworkProxyRouting
*** NetworkSecurityProtocols
*** OperatingSystemSecurity
*** PenetrationTestingMethods
*** UseSyntheticData
*** VirtualisationSecurity
*** VulnerabilityTestingMethods
*** WebBrowserSecurity
*** WebSecurityProtocols
*** WirelessSecurityProtocols

@endwbs
