@startuml
!include style.plantuml
'left to right direction

class Thing #silver

package dpv {
    class Technology
}

package tech {
    class ProvisionMethod
    class Documentation
    class IntendedUse
    class TechnologyStatus
}

package ai {
    class AI
    class AISystem
    class Capability
    class Measure
    class Model
    class GPAIModel
    class Technique
    class Data
    class RiskConcept
    class Measure
    class LifecycleStage
    class AIBias
    RiskConcept <|-- AIBias
    class DataRisk
    RiskConcept <|-- DataRisk
    AI -- RiskConcept : risk:hasRiskSource\ndpv:hasRisk\ndpv:hasConsequence\ndpv:hasImpact >
    AI -- Data : ai:hasData >
    AI -- LifecycleStage : ai:hasLifecycleStage
}

Thing -- AI : dpv:isImplementedUsingTechnology >
Technology <|-- AI
Technology -- ProvisionMethod : tech:hasProvisionMethod >
Technology -- Documentation : tech:hasDocumentation >
Technology -- IntendedUse : tech:hasIntendedUse >
Technology -- TechnologyStatus : dpv:hasStatus >
AI -up- Capability : ai:hasCapability >
AI -- Measure : ai:hasMeasure >
AI <|-up- Model
AI <|-up- AISystem
Model <|-right- GPAIModel
AI -- Technique : ai:hasTechnique >

@enduml

