@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
	class LegalBasis
	class Consent
	class InformedConsent
	class ExpressedConsent
	class ImpliedConsent
	class UninformedConsent

	class ConsentStatus #LightBlue
	class ConsentStatusInvalidForProcessing #LightBlue
	class ConsentStatusValidForProcessing #LightBlue
	class ConsentExpired #LightBlue
	class ConsentInvalidated #LightBlue
	class ConsentRefused #LightBlue
	class ConsentRequestDeferred #LightBlue
	class ConsentRequested #LightBlue
	class ConsentRevoked #LightBlue
	class ConsentUnknown #LightBlue
	class ConsentWithdrawn #LightBlue
	class ConsentGiven #LightBlue
	class RenewedConsentGiven #LightBlue

	class Duration
	note right of Duration : e.g. 6 months,31-DEC-2024,\nuntil account closure

	class ConsentControl
	class ObtainConsent
	class ProvideConsent
	class ReaffirmConsent
}

Thing -- LegalBasis: hasLegalBasis >
LegalBasis <|-l- Consent
Consent -l- ConsentStatus: hasConsentStatus >
Consent -r- ConsentControl: hasConsentControl >
ConsentStatus <|-- ConsentStatusValidForProcessing
ConsentStatus <|-- ConsentStatusInvalidForProcessing

ConsentControl <|-- ObtainConsent
ConsentControl <|-- ProvideConsent
ConsentControl <|-- ReaffirmConsent

Consent <|-- InformedConsent
InformedConsent <|-- ExpressedConsent
InformedConsent <|-- ImpliedConsent
Consent <|-- UninformedConsent

ConsentStatusInvalidForProcessing <|-- ConsentExpired
ConsentStatusInvalidForProcessing <|-- ConsentInvalidated
ConsentStatusInvalidForProcessing <|-- ConsentRefused
ConsentStatusInvalidForProcessing <|-- ConsentRequestDeferred
ConsentStatusInvalidForProcessing <|-- ConsentRequested
ConsentStatusInvalidForProcessing <|-- ConsentRevoked
ConsentStatusInvalidForProcessing <|-- ConsentUnknown
ConsentStatusInvalidForProcessing <|-- ConsentWithdrawn
ConsentStatusValidForProcessing <|-- ConsentGiven
ConsentStatusValidForProcessing <|-- RenewedConsentGiven

Consent -- Duration : hasDuration >


@enduml
