@startuml
!include style.plantuml
'left to right direction
top to bottom direction

class Thing #silver
package dpv {
	class Consequence
	class Impact
	class ConsequenceAsSideEffect
	class ConsequenceOfFailure
	class ConsequenceOfSuccess
	class Benefit
	class Damage
	class Detriment
	class Harm
	class MaterialDamage
	class NonMaterialDamage
}
Thing -- Consequence : hasConsequence >
Consequence <|-– Impact
Consequence <|-– ConsequenceAsSideEffect
Consequence <|-– ConsequenceOfFailure
Consequence <|-– ConsequenceOfSuccess
Impact <|-- Benefit
Impact <|-- Damage
Impact <|-- Detriment
Damage <|-- Harm
Damage <|-- MaterialDamage
Damage <|-- NonMaterialDamage

@enduml
