@startuml
!include style.plantuml
top to bottom direction

class "Thing" as Thing1 #silver
class "Thing" as Thing2 #silver
class "Thing" as Thing3 #silver
class "Thing" as Thing4 #silver

package dpv {
	class Context
	class Importance
	class Necessity
	class Entity
	class Technology
	class Justification
	class Frequency
	class Duration
	class Scope
	class Status
	class ActivityStatus
	class AuditStatus
	class RequestStatus
	class ComplianceStatus
	class Lawfulness
}

Thing1 -d- Context: hasContext >
Thing1 -d- Importance: hasImportance >
Thing1 -d- Necessity: hasNecessity >
Thing1 -d- Entity: hasEntity >
Thing2 -u- Technology: hasTechnology >
Thing2 -u- Justification: hasJustification >
Thing3 -u- Frequency: hasFrequency >
Thing3 -u- Duration: hasDuration >
Thing3 -u- Scope: hasScope >
Thing3 -u- Status: hasStatus >
Thing4 -d- ActivityStatus: hasActivityStatus >
Thing4 -d- AuditStatus: hasAuditStatus >
Thing4 -d- RequestStatus: hasRequestStatus >
Thing4 -d- ComplianceStatus: hasComplianceStatus >
Thing4 -d- Lawfulness: hasLawfulness >

Thing2 -r- Resource: hasIdentifier >
Thing2 -r- Resource: hasOutcome >
Thing2 -l- Resource: isAfter >
Thing2 -l- Resource: isBefore >

@enduml
