@startuml
!include style.plantuml
left to right direction

class Thing #silver
() Resource
package dpv {
	class Entity
}

Thing -- Entity: hasEntity >
Entity -- Resource : hasName >
Entity -- Resource : hasAddress >
Entity -- Resource : hasContact >
Entity -- Resource : hasRepresentative >
Entity -- Resource : hasJurisdiction >
Entity -- Resource : hasLocation >

@enduml
