@startmindmap
!include style.plantuml
* dpv:Principle
** eu-gdpr:AccountabilityPrinciple
** eu-gdpr:AccuracyPrinciple
** eu-gdpr:DataMinimisationPrinciple
** eu-gdpr:FairnessPrinciple
** eu-gdpr:IntegrityConfidentialityPrinciple
** eu-gdpr:LawfulnessPrinciple
** eu-gdpr:PurposeLimitationPrinciple
** eu-gdpr:StorageLimitationPrinciple
** eu-gdpr:TransparencyPrinciple
@endmindmap
