@startmindmap
!include style.plantuml
+ dpv:Right
++ eu-gdpr:A13
++ eu-gdpr:A14
++ eu-gdpr:A15
++ eu-gdpr:A16
++ eu-gdpr:A17
++ eu-gdpr:A18
++ eu-gdpr:A19
++ eu-gdpr:A20
++ eu-gdpr:A21
++ eu-gdpr:A22
-- eu-gdpr:A7-3
-- eu-gdpr:A77
-- eu-gdpr:DirectDataCollectionNotice
-- eu-gdpr:IndirectDataCollectionNotice
-- eu-gdpr:RightsRecipientsNotice
-- eu-gdpr:SARNotice
@endmindmap
