@startuml
!include style.plantuml
skinParam groupInheritance 2

'class Thing #silver
package dpv {
	class Process
	class LegalBasis
}
package dpv.legal.eu.gdpr {
	class A6_1_a as "A6-1-a"
	class A6_1_a_explicit_consent as "A6-1-a-explicit-consent"
	class A6_1_a_non_explicit_consent as "A6-1-a-non-explicit-consent"
	class A6_1_b as "A6-1-b"
	class A6_1_b_contract_performance as "A6-1-b-contract-performance"
	class A6_1_b_enter_into_contract as "A6-1-b-enter-into-contract"
	class A6_1_c as "A6-1-c"
	class A6_1_d as "A6-1-d"
	class A6_1_d_data_subject as "A6-1-d-data-subject"
	class A6_1_d_natural_person as "A6-1-d-natural-person"
	class A6_1_e as "A6-1-e"
	class A6_1_e_official_authority as "A6-1-e-official-authority"
	class A6_1_e_public_interest as "A6-1-e-public-interest"
	class A6_1_f as "A6-1-f"
	class A6_1_f_controller as "A6-1-f-controller"
	class A6_1_f_third_party as "A6-1-f-third-party"
}
'Thing <|- Process
Process - LegalBasis: hasLegalBasis >

LegalBasis <|-- A6_1_a
LegalBasis <|-- A6_1_b
LegalBasis <|-- A6_1_c
LegalBasis <|-- A6_1_d
LegalBasis <|-- A6_1_e
LegalBasis <|-- A6_1_f
A6_1_a <|-- A6_1_a_explicit_consent
A6_1_a <|-- A6_1_a_non_explicit_consent
A6_1_b <|-- A6_1_b_contract_performance
A6_1_b <|-- A6_1_b_enter_into_contract
A6_1_d <|-- A6_1_d_data_subject
A6_1_d <|-- A6_1_d_natural_person
A6_1_e <|-- A6_1_e_official_authority
A6_1_e <|-- A6_1_e_public_interest
A6_1_f <|-- A6_1_f_controller
A6_1_f <|-- A6_1_f_third_party

@enduml
