@startmindmap
!include style.plantuml

+ LegalBasis
++ Consent
+++ InformedConsent
++++ ExpressedConsent
+++++ ExplicitlyExpressedConsent
++++ ImpliedConsent
+++ UninformedConsent
++ Contract
+++ EnterIntoContract
+++ ContractPerformance
-- DataTransferLegalBasis
-- LegalObligation
-- LegitimateInterest
--- LegitimateInterestOfController
--- LegitimateInterestOfDataSubject
--- LegitimateInterestOfThirdParty
-- OfficialAuthorityOfController
-- PublicInterest
-- VitalInterest
--- VitalInterestOfNaturalPerson
---- VitalInterestOfDataSubject

@endmindmap
