@startwbs

* OrganisationalMeasure
** Assessment
*** ComplianceAssessment
*** ConformanceAssessment
*** DataInteroperabilityAssessment
*** DataQualityAssessment
*** EffectivenessDeterminationProcedures
*** LegitimateInterestAssessment
** CertificationSeal
*** Certification
*** Seal
** Consultation
*** ConsultationWithAuthority
*** ConsultationWithDataSubject
*** ConsultationWithDPO
** DigitalLiteracy
*** AILiteracy
*** DataLiteracy
** GovernanceProcedures
*** AssetManagementProcedures
*** ComplianceMonitoring
*** DisasterRecoveryProcedures
*** IncidentManagementProcedures
*** IncidentReportingCommunication
*** Policy
*** ReviewProcedure
*** StandardsConformance
** GuidelinesPrinciple
*** CodeOfConduct
*** DesignStandard
*** Guideline
*** Principle
*** PrivacyByDefault
*** PrivacyByDesign
** Notice
*** DataTransferNotice
*** PrivacyNotice
*** SecurityIncidentNotice
** Notification
*** SecurityIncidentNotification
** RecordsOfActivities
*** DataBreachRecord
*** DataProcessingRecord
*** SecurityIncidentRecord
** RightsManagement
*** DataSubjectRightsManagement
*** IPRManagement
*** PermissionManagement
** Safeguard
*** RegulatorySandbox
*** SafeguardForDataTransfer
** SecurityProcedure
*** AuthorisationProcedure
*** BackgroundChecks
*** DataSecurityManagement
*** SecureProcessingEnvironment
*** SecurityRoleProcedures
*** ThirdPartySecurityProcedures
** StaffTraining
*** CybersecurityTraining
*** DataProtectionTraining
*** EducationalTraining
*** ProfessionalTraining
*** SecurityKnowledgeTraining
** SupportEntityDecisionMaking
*** SupportContractNegotiation
*** SupportExchangeOfViews
*** SupportInformedConsentDecision

@endwbs
