@startuml
hide methods
hide circles

class Thing #silver

package dpv {
    class Location {
        String iso_alpha2
        String iso_alpha3
        String iso_numeric
        String un_m49
    }
    class City
    class Region
    class Country
    class SupraNationalUnion
}

Thing -- Location : hasLocation >
Location .. City : rdf:type >
Location .. Region : rdf:type >
Location .. Country : rdf:type >
Location .. SupraNationalUnion : rdf:type >
Location -- Location : skos:broader\nskos:narrower >
Location .. EU_Vocabularies : skos:exactMatch >

@enduml