@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class VulnerableDataSubject
	class DataSubject
	class Child
}
Thing -- DataSubject: hasDataSubject >
DataSubject <|-- Child
DataSubject <|-- VulnerableDataSubject

@enduml
