@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
	class Processing
	class DataSource
	class ProcessingContext
	class Context
}
Thing -- Processing : hasProcessing >
Processing -- DataSource: hasDataSource >
Processing -- ProcessingContext : hasContext >
Context <|- ProcessingContext

@enduml
