@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Representative
	class DataController
	class DataProtectionOfficer
}
Thing -- DataController: hasDataController >
DataController -- Representative: hasRepresentative >
Representative <|-- DataProtectionOfficer

@enduml
