@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Location
	class Authority
	class Law
	class Country
}
Location <|-- Country
Thing -- Authority: hasAuthority >
Authority -- Thing: isAuthorityFor >
Thing -- Location: hasLocation >
Thing -- Location: hasJurisdiction >
Thing -- Country: hasCountry >
Location -- Law: hasApplicableLaw >

@enduml
