@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Risk
	class RiskMitigationMeasure
	class TechnicalOrganisationalMeasure
}
Thing -- Risk : hasRisk >
TechnicalOrganisationalMeasure <|-- RiskMitigationMeasure
Risk -- RiskMitigationMeasure : mitigatesRisk <
RiskMitigationMeasure -- Risk : isMitigatedByMeasure <

@enduml
