@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
	class Representative
	class DataController
	class DataProcessor
	class ThirdParty
	class Authority
	class DataSubject
	class LegalEntity
	class NaturalPerson
	class Entity
}
Representative --|> LegalEntity 
DataController --|> LegalEntity
DataProcessor --|> LegalEntity
ThirdParty --|> LegalEntity
Authority --|> LegalEntity
DataSubject --|> LegalEntity
DataSubject --|> NaturalPerson
LegalEntity --|> Entity
NaturalPerson --|> Entity

Thing -- Representative: hasRepresentative >
Thing -- DataController: hasDataController >
Thing -- DataProcessor: hasDataProcessor >
Thing -- ThirdParty: hasThirdParty >
Thing -- Authority: hasAuthority >
Thing -- DataSubject: hasDataSubject >

@enduml
