@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Technology
	class Entity
	class Location
}
package dpv.tech {
	class Actor
	class Capability
	class ProvisionMethod
	class CommunicationMechanism
	class InputOutput
	class Documentation
	class DeploymentLocation
	class Function
	class IntendedUse
}
' Technology
Thing -- Technology: isImplementedUsingTechnology >
Technology -- Thing: implements >

' Actor
Entity <|-- Actor
Technology -- Actor: hasActor >

' Capability
Technology -- Capability: hasCapability >

' ProvisionMethod
Technology <|-- ProvisionMethod
Technology -- ProvisionMethod: hasProvisionMethod >

' CommunicationMechanism
Technology <|-- CommunicationMechanism
Technology -- CommunicationMechanism: hasCommunicationMechanism >

' InputOutput

' Documentation
Technology -- Documentation: hasDocumentation >

' DeploymentLocation
Location <|-- DeploymentLocation
Technology -- DeploymentLocation: hasDeploymentLocation >

' Function
Technology -- Function: hasFunction >

' IntendedUse
Technology -- IntendedUse: hasIntendedUse >

@enduml
