@startmindmap
!include style.plantuml

+ Data
++ CollectedData
+++ ObservedData
+++ ProvidedData
++ CommerciallyConfidentialData
++ ConfidentialData
+++ IntellectualPropertyData
+++ StatisticallyConfidentialData
++ DerivedData
+++ InferredData
++ GeneratedData
+++ SyntheticData
++ IncorrectData
++ NonPersonalData
+++ AnonymisedData
++ SensitiveData
+++ SensitiveNonPersonalData
++ UnverifiedData
++ VerifiedData
-- PersonalData
--- CollectedPersonalData
--- DerivedPersonalData
--- GeneratedPersonalData
--- IdentifyingPersonalData
--- PseudonymisedData
--- SensitivePersonalData

@endmindmap