@startuml
!include style.plantuml
left to right direction
'top to bottom direction

class Thing #silver
package dpv {
	class Entity
	class Risk
	class RiskMitigationMeasure
	class RiskLevel
	class Consequence
	class Impact
	class Severity
	class Likelihood
}

Thing -- Risk : hasRisk >
Thing -- Consequence: hasConsequence >
Consequence -- Thing: hasConsequenceOn >
Thing -- Impact: hasImpact >
Impact -d- Entity: hasImpactOn >
Thing -- Severity: hasSeverity >
Thing -- Likelihood: hasLikelihood >
Risk -- Risk: hasResidualRisk >
Risk -- RiskMitigationMeasure : isMitigatedByMeasure >
Risk -- RiskLevel: hasRiskLevel >

@enduml
