@startuml

!include style.plantuml
left to right direction
'top to bottom direction
'skinparam linetype ortho

class Thing #silver
package dpv {
	class TechnicalOrganisationalMeasure
	class TechnicalMeasure
	class OrganisationalMeasure
	class LegalMeasure
	class PhysicalMeasure
}

TechnicalOrganisationalMeasure <|-u- TechnicalMeasure
TechnicalOrganisationalMeasure <|-u- OrganisationalMeasure
TechnicalOrganisationalMeasure <|-u- LegalMeasure
TechnicalOrganisationalMeasure <|-u- PhysicalMeasure

Thing -- TechnicalOrganisationalMeasure : hasTechnicalOrganisationalMeasure >
Thing -- OrganisationalMeasure : hasOrganisationalMeasure >
Thing -- TechnicalMeasure : hasTechnicalMeasure >
Thing -- LegalMeasure : hasLegalMeasure >
Thing -- PhysicalMeasure : hasPhysicalMeasure >


@enduml
