@startuml
!include style.plantuml
skinParam groupInheritance 2

package dpv {
	class Process
	class LegalBasis
}
package dpv.legal.eu.gdpr {
	class A9_2_a as "A9-2-a"
	class A9_2_b as "A9-2-b"
	class A9_2_c as "A9-2-c"
	class A9_2_d as "A9-2-d"
	class A9_2_e as "A9-2-e"
	class A9_2_f as "A9-2-f"
	class A9_2_g as "A9-2-g"
	class A9_2_h as "A9-2-h"
	class A9_2_i as "A9-2-i"
	class A9_2_j as "A9-2-j"
}

Process -- LegalBasis: hasLegalBasis >

LegalBasis <|-- A9_2_a
LegalBasis <|-- A9_2_b
LegalBasis <|-- A9_2_c
LegalBasis <|-- A9_2_d
LegalBasis <|-- A9_2_e
LegalBasis <|-- A9_2_f
LegalBasis <|-- A9_2_g
LegalBasis <|-- A9_2_h
LegalBasis <|-- A9_2_i
LegalBasis <|-- A9_2_j

@enduml
