@startwbs
!include style.plantuml

* dpv:ProcessingScale
** dpv:DataSubjectScale
*** dpv:HugeScaleOfDataSubjects
*** dpv:LargeScaleOfDataSubjects
*** dpv:MediumScaleOfDataSubjects
*** dpv:SingularScaleOfDataSubjects
*** dpv:SmallScaleOfDataSubjects
*** dpv:SporadicScaleOfDataSubjects
** dpv:DataVolume
*** dpv:HugeDataVolume
*** dpv:LargeDataVolume
*** dpv:MediumDataVolume
*** dpv:SingularDataVolume
*** dpv:SmallDataVolume
*** dpv:SporadicDataVolume
** dpv:GeographicCoverage
*** dpv:GlobalScale
*** dpv:LocalEnvironmentScale
*** dpv:LocalityScale
*** dpv:MultiNationalScale
*** dpv:NationalScale
*** dpv:NearlyGlobalScale
*** dpv:RegionalScale
** dpv:ProcessingScale
*** dpv:LargeScaleProcessing
*** dpv:MediumScaleProcessing
*** dpv:SmallScaleProcessing

@endwbs