@startuml
!include style.plantuml

package dpv {
    class Process
    class Data
    class PersonalData
    class Processing
    class LegalBasis
    class Entity
    class TechnicalMeasure
    class OrganisationalMeasure
    class "Process" as Process2
    class Service
}

Process -- Data : hasData >
Process -- PersonalData : hasPersonalData >
Process -- Processing : hasProcessing >
Process -- LegalBasis : hasLegalBasis >
Process -- Entity : hasEntity >
Process -- TechnicalMeasure : hasTechnicalMeasure >
Process -- OrganisationalMeasure : hasOrganisationalMeasure >

Process -r- Process2 : hasProcess >
Service -r- Process : hasProcess >

@enduml