@startuml
!include style.plantuml

class Thing #silver

package dpv {
    class Entity
    class EntityInvolvement
    class EntityPermissiveInvolvement
    class EntityNonPermissiveInvolvement
    class EntityActiveInvolvement
    class EntityPassiveInvolvement
    class EntityNonInvolvement
    class HumanInvolvement
    class AutomationLevel
}


Thing -- EntityInvolvement : hasEntityInvolvement >
EntityInvolvement <|-- EntityPermissiveInvolvement
EntityInvolvement <|-- EntityNonPermissiveInvolvement
EntityInvolvement <|-- EntityActiveInvolvement
EntityInvolvement <|-- EntityPassiveInvolvement
EntityInvolvement <|-- EntityNonInvolvement
EntityInvolvement <|-- HumanInvolvement

Thing -- Entity : hasActiveEntity >
Thing -- Entity : hasPassiveEntity >
Thing -- Entity : hasNonInvolvementEntity >
Thing -- Entity : isDeterminedByEntity >

Thing -- HumanInvolvement : hasHumanInvolvement >
Thing -- AutomationLevel : hasAutomationLevel >

@enduml