@startuml
hide methods
hide circles
left to right direction

class Thing #silver 

    class Law {
        IRI foaf:homepage
    }
    class Authority {
        IRI foaf:homepage
    }
    class DataProtectionAuthority {
        IRI foaf:homepage
    }
    class Location

Thing -- Law : hasLaw >
Thing -- Authority : hasAuthority >
Authority <|-- DataProtectionAuthority
Authority -- Law : hasApplicableLaw >
Authority -- Location : hasJurisdiction >
Location -- Authority : hasAuthority >
Thing -- Location : hasJurisdiction >

@enduml