@startuml
!include style.plantuml

class Thing #silver
package dpv {
    class Entity
    class AutomationLevel
    class EntityInvolvement
    class EntityPermissiveInvolvement
    class EntityNonPermissiveInvolvement
    class EntityActiveInvolvement
    class EntityPassiveInvolvement
    class EntityNonInvolvement
    class HumanInvolvement
    class ProcessingCondition
    class StorageCondition
    class DataSource
    class DataSubjectScale
    class DataVolume
    class ProcessingScale
    class GeographicCoverage
}

Thing -- AutomationLevel : hasAutomationLevel >
Thing -- EntityInvolvement : hasEntityInvolvement >
EntityInvolvement <|-- EntityPermissiveInvolvement
EntityInvolvement <|-- EntityNonPermissiveInvolvement
EntityInvolvement <|-- EntityActiveInvolvement
EntityInvolvement <|-- EntityPassiveInvolvement
EntityInvolvement <|-- EntityNonInvolvement
EntityInvolvement <|-- HumanInvolvement

Thing -- Entity : hasActiveEntity\nhasPassiveEntity\nhasNonInvolvementEntity\nisDeterminedByEntity >
Thing -- ProcessingCondition : hasProcessingCondition >
Thing -- StorageCondition : hasStorageCondition >
ProcessingCondition <|-- StorageCondition
Thing -- HumanInvolvement : hasHumanInvolvement >
Thing -- DataSource : hasDataSource >
Thing -- DataSubjectScale : hasDataSubjectScale >
Thing -- DataVolume : hasDataVolume >
Thing -- ProcessingScale : hasProcessingScale >
Thing -- GeographicCoverage : hasGeographicCoverage >


@enduml