@startuml
!include style.plantuml
'left to right direction

package dpv {
    class Rule
    class Deterrence
    class Recommendation
    class Obligation
    class Prohibition
    class Permission
}
class Thing #silver

Thing -- Rule : hasRule >
Thing -- Deterrence : hasDeterrence >
Thing -- Recommendation : hasRecommendation >
Thing -- Obligation : hasObligation >
Thing -- Prohibition : hasProhibition >
Thing -- Permission : hasPermission >

Rule <|-u- Deterrence 
Rule <|-u- Recommendation
Rule <|-u- Obligation
Rule <|-u- Prohibition
Rule <|-u- Permission

@enduml
