@startuml
!include style.plantuml
left to right direction

class Thing #silver

package dpv {
    class Technology
}

package tech {
    class ProvisionMethod
    class Documentation
    class IntendedUse
    class TechnologyStatus
}

package ai {
    class AI
    class AISystem
    class Capability
    class Measure
    class Model
    class Risk
    class Technique
}

Thing -- AI : dpv:isImplementedUsingTechnology >
Technology <|-- AI
AI -- ProvisionMethod : tech:hasProvisionMethod >
AI -- Documentation : tech:hasDocumentation >
AI -- IntendedUse : tech:hasIntendedUse >
AI -- TechnologyStatus : dpv:hasStatus >
AI -- Capability : ai:hasCapability >
AI -- Measure : ai:hasMeasure >
AI <|-- Model
AI <|-- AISystem
AI -- Risk : dpv:hasRisk >
AI -- Technique : ai:hasTechnique >

@enduml

