@startwbs
!include style.plantuml

* Entity
** NaturalPerson
*** DataSubject
**** Adult
**** Child
**** ParentOfDataSubject
**** VulnerableDataSubject
**** ...
** LegalEntity
*** DataController
*** JointDataControllers
*** DataExporter
*** Recipient
**** DataImporter
**** DataProcessor
**** ThirdParty
*** ServiceConsumer
*** ServiceProvider
*** Representative
** Organisation
*** GovernmentalOrganisation
**** Authority
***** DataProtectionAuthority
***** ...
*** AcademicScientificOrganisation
*** ForProfitOrganisation
*** NonGovernmentalOrganisation
*** NonProfitOrganisation
*** ...

@endwbs