@startuml
!include style.plantuml
top to bottom direction

class Thing #silver
package dpv {
	class Entity
	note right: hasName\nhasAddress\nhasContact\nhasIdentifier
	class Representative
	class Jurisdiction
	class Location
}

Thing -- Entity: hasEntity >
Entity -- Representative : hasRepresentative >
Entity -- Jurisdiction : hasJurisdiction >
Entity -- Location : hasLocation >

@enduml
