@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
	class StorageDuration
	class StorageLocation
	class StorageDeletion
	class StorageRestoration
	class StorageCondition
}
Thing -- StorageCondition: hasStorage >
Thing -- StorageDuration : hasDuration >
Thing -- StorageLocation: hasLocation >

StorageCondition <|-- StorageDuration
StorageCondition <|-- StorageLocation
StorageCondition <|-- StorageDeletion
StorageCondition <|-- StorageRestoration

@enduml
