@startuml
!include style.plantuml
left to right direction
top to bottom direction

class Thing #silver
package dpv {
	class Technology
	class Entity
}

package tech {
    class Actor
    class IntendedUse
    class Function
    class ProvisionMethod
    class CommunicationMechanism
    class Documentation
    class Capability
    class DeploymentLocation
}

Thing -- Technology: isImplementedUsingTechnology >
Technology -- Entity: isImplementedByEntity >
Technology -- Actor: hasActor >
Technology -- IntendedUse: hasIntendedUse >
Technology -- Function: hasFunction >
Technology -- ProvisionMethod: hasProvisionMethod >
Technology -- CommunicationMechanism: hasCommunicationMechanism >
Technology -- Documentation: hasDocumentation >
Technology -- Capability: hasCapability >
Technology -- DeploymentLocation: hasDeploymentLocation >

@enduml
