@startwbs
!include style.plantuml

* PersonalData
** Sensitive*
*** Special Category*
** Internal
*** Preferences
*** Knowledge
*** Beliefs
*** ...
** External
*** Behavioural
*** Demographics
*** Physical
*** Sexual
*** Identifying
*** ...
** Household
*** personal activities
*** household activities
*** ...
** Social
*** Family
*** Friends
*** Professional
*** Public Life
*** Communication
*** ...
** Financial
*** Transactional
*** Ownership
*** Financial Account
*** ..
** Tracking
*** Location
*** Device based
*** Contact
*** ...
** Historical
*** Life History
*** ...

@endwbs