@startuml
!include style.plantuml

class Thing #silver
package dpv {
    class Processing
    class Copy
    class Disclose
    class Obtain
    class Organise
    class "Remove" as R
    class Store
    class Transfer
    class Transform
    class Use
    class Access
    class Analyse
    class Assess
    class Consult
    class Monitor
    class Query
    class Match
    class Profiling
    class Retrieve
    class Acquire
    class Collect
    class Derive
    class Infer
    class Generate
    class Observe
    class Record
    class Destruct
    class Erase
    class Delete
    class Transfer
    class Move
    class CrossBorderTransfer
    class Adapt
    class Align
    class Alter
    class Modify
    class Anonymise
    class Combine
    class Aggregate
    class Filter
    class Pseudonymise
    class Restrict
    class Screen
    class Download
    class Export
    class Display
    class Disseminate
    class MakeAvailable
    class Share
    class Transmit
    class Structure
    class Format
    class Reformat
    class DiscloseByTransmission
}


Thing -- Processing : hasProcessing >

Processing <|-- Copy    
Processing <|-- Disclose    
Processing <|-- Obtain  
Processing <|-- Organise    
Processing <|-- R  
Processing <|-- Store   
Processing <|-- Transfer    
Processing <|-- Transform   
Processing <|-- Use 
Use <|-- Access
Use <|-- Analyse
Use <|-- Assess
Use <|-- Consult
Consult <|-- Monitor
Consult <|-- Query
Use <|-- Match
Use <|-- Profiling
Use <|-- Retrieve
Obtain <|-- Acquire
Obtain <|-- Collect
Obtain <|-- Derive
Derive <|-- Infer
Obtain <|-- Generate
Obtain <|-- Observe
Obtain <|-- Record
Transfer <|-- Move
Transfer <|-- CrossBorderTransfer
Transform <|-- Adapt
Transform <|-- Align
Transform <|-- Alter
Alter <|-- Modify
Transform <|-- Anonymise
Transform <|-- Combine
Alter <|-- Aggregate
Transform <|-- Filter
Transform <|-- Pseudonymise
Transform <|-- Restrict
Transform <|-- Screen
Disclose <|-- Download
Disclose <|-- Export
Disclose <|-- Display
Disclose <|-- DiscloseByTransmission
Disclose <|-- Disseminate
Disclose <|-- MakeAvailable
Disclose <|-- Share
Disclose <|-- Transmit
Organise <|-- Structure
Structure <|-- Format
Format <|-- Reformat
R <|-- Erase
R <|-- Destruct
R <|-- Delete

' layout tweak
Anonymise -[hidden]-> Disclose
CrossBorderTransfer -[hidden]-> Obtain
Display -[hidden]-> R
Observe -[hidden]-> Use

@enduml