@startuml
hide attributes
hide methods
hide circles
left to right direction

package dpv {}

package "de-gdng" as gdng {
	 dpv.Processing <|-- gdng.DataLinkage
	 dpv.Data <|-- gdng.PseudonymizedData
	 dpv.Process <|-- gdng.DataLinkageRequest
	 dpv.Data <|-- gdng.DataLinkageRequestRecord
	 dpv.Data <|-- gdng.DataLinkagePermission
}

@enduml
