@startuml
hide attributes
hide methods
hide circles
left to right direction

package dpv {}

package "de-gdng" as gdng {
	dpv.Process <|-- gdng.HealthDataQuery
	dpv.Data <|-- gdng.HealthDataQueryRecord
	dpv.Service <|-- gdng.PublicMetadataCatalogue

	dpv.Process <|-- HealthDataAccessApplication
	dpv.Data <|-- HealthDataAccessApplicationRecord
	dpv.Service <|-- PublicHealthDataAccessApplicationRegister
	
	dpv.SecureProcessingEnvironment <|-- gdng.SecureProcessingEnvironment
}

@enduml
