@startuml
hide attributes
hide methods
hide circles
left to right direction

package dpv {}
package "sector-health" as health {}
package "eu-gdpr" as gdpr {}

package "de-gdng" as gdng {
	gdpr.HealthData <|-- gdng.HealthData
	gdpr.PersonalData <|-- gdng.PersonalData
	health.SecondaryUse <|-- gdng.SecondaryUse
	gdng.ResearchProject <|-- gdng.HealthAndHealthcareResearchProject
	dpv.Process <|-- gdng.ResearchProject
}

@enduml
