@startuml
hide attributes
hide methods
hide circles
left to right direction

package dpv {}

package "de-gdng" as gdng {
    ' classes with differing labels
    class P6_1 as "P6-1"
    class P6_3_Consent as "P6-3-Consent"
    class P6_3_Statutory as "P6-3-Statutory"
    class P6_3_PublicJointResearch as "P6-3-PublicJointResearch"

    dpv.Processing <|- gdng.HealthcareDataProcessing

    dpv.Purpose <|--- gdng.QualityAssurance
    dpv.Purpose <|--- gdng.PromotionOfPatientSafety
    dpv.Purpose <|--- gdng.MedicalRehabNursingResearch
    dpv.Purpose <|--- gdng.Statistics

    dpv.LegalBasis <|-- gdng.P6_1
    dpv.Transfer <|-- gdng.Transfer
    dpv.Necessity <|-- gdng.Necessity
    dpv.Conformant <|-- gdng.ProcessingRequirementsConformance
    dpv.LegitimateInterest <|-- gdng.LegitimateInterest
    dpv.LegalMeasure <|-- gdng.DPAApproval

    dpv.LegalBasis <|-- gdng.P6_3_Consent
    dpv.LegalBasis <|-- gdng.P6_3_Statutory
    dpv.LegalBasis <|-- gdng.P6_3_PublicJointResearch

    dpv.TechnicalOrganisationalMeasure <|--- gdng.PseudonymizationOfData
    dpv.TechnicalOrganisationalMeasure <|--- gdng.AnonymizationOfData
    dpv.TechnicalOrganisationalMeasure <|--- gdng.AnonymizationOfProcessingResults
    dpv.TechnicalOrganisationalMeasure <|--- gdng.RightsRolesConcept

    dpv.DataDeletionPolicy <|-- gdng.DeletionPolicy
    dpv.LegalObligation <|-- gdng.DutyToInform
}

@enduml
