@startuml
hide attributes
hide methods
hide circles
left to right direction

package dpv {}

package "sector-health" as health {}

package "eu-gdpr" as gdpr {}

package "de-gdng" as gdng {
	dpv.Organisation <|--  gdng.DataProcessingHealthcareFacility
	dpv.Authority <|-- gdng.DataAccessAndCoordinationOffice
	health.HealthDataHolder <|-- gdng.HealthDataHolder
	health.HealthDataUser <|-- gdng.HealthDataUser

	gdng.HealthDataHolder <|-- gdng.DataInfrastructure
	gdng.HealthDataHolder <|-- gdng.DataPlatform
	gdng.HealthDataHolder <|-- gdng.RegulatedHealthDataHolder
	gdng.HealthDataHolder <|-- gdng.ResponsibleDataHoldingAndMediatingBody
	gdng.HealthDataHolder <|-- gdng.FederalStateCentresForCancerRegistryData

	gdng.RegulatedHealthDataHolder <|-- gdng.HealthDataLab
	gdng.RegulatedHealthDataHolder <|-- gdng.GermanCentreForCancerRegistryData
	gdng.RegulatedHealthDataHolder <|-- gdng.ModelProjectGenomeSequencingPlatform

	dpv.LegalEntity <|-- gdng.PublicJointHealthResearchNetwork

	gdpr.Controller <|-- gdng.Controller
	gdpr.DataSubject <|-- gdng.DataSubject
	gdpr.ThirdParty <|-- gdng.ThirdParty

	dpv.Entity <|-- gdng.AuthorizedPerson

}

@enduml
